using Pkg

Pkg.add("PyCall")
Pkg.add("ArgParse")
Pkg.add("Distributions")
Pkg.add("PyPlot")
Pkg.add("ProfileView")
Pkg.add("HDF5")
Pkg.add("JLD")
#Pkg.add("Gradfly")
Pkg.add("ProgressMeter")
Pkg.add("ProgressBars")
Pkg.add("MultivariateStats")
Pkg.add("LightGraphs")
Pkg.add("Compose")
Pkg.add("GraphPlot")
Pkg.add("Plots")
Pkg.add("MCMCDiagnostics")
Pkg.add("QuadGK")
Pkg.add("SpecialFunctions")
